version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/eduai
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'